-- CREATE TABLE users (
--     id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
--     name VARCHAR(100) NOT NULL,
--     age INT NOT NULL
-- );
-- INSERT INTO user (id, name, age)
-- VALUES  ("a1b","Nguyen Van A","20"),
--         ("a2b","Nguyen Van B","30"),
--         ("a3b","Luong Tan Tai","21");

-- SELECT * FROM users WHERE id = 'a1b';
